version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'security_db'
      MYSQL_USER: 'samativrsk'
      MYSQL_PASSWORD: 'Webmoneyruskach4898'
      MYSQL_ROOT_PASSWORD: 'Webmoneyruskach4898'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
